tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-versions"
tap "homebrew/core"

# cli
brew "asdf"
brew "bat"
brew "cmake"
brew "eza"
brew "fd"
brew "gh"
brew "git"
brew "ripgrep"
brew "starship"
brew "webp"
brew "zellij"
brew "zsh-autosuggestions"
brew "zsh-completions"
brew "zsh-syntax-highlighting"

# app
cask "alacritty"
cask "jetbrains-toolbox"
cask "powershell"
cask "visual-studio-code"
