import = [
    "~/.config/alacritty/themes/fleet-dark-like.toml"
]

[env]
TERM = "alacritty"

[font]
size = 14

[font.bold]
family = "UDEV Gothic 35NF"
style = "Bold"

[font.bold_italic]
family = "UDEV Gothic 35NF"
style = "Bold Italic"

[font.italic]
family = "UDEV Gothic 35NF"
style = "Italic"

[font.normal]
family = "UDEV Gothic 35NF"
style = "Regular"

[shell]
args = ["-l", "-c", "zellij attach --index 0 --create"]
program = "/bin/zsh"

[window]
opacity = 0.95

[window.dimensions]
columns = 160
lines = 48

[window.padding]
x = 8
y = 8
