"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true

format = """
$username\
$directory\
$git_branch\
$line_break\
$character"""

[directory]
truncation_length = 8
truncate_to_repo = false
truncation_symbol = "…/"

[character]
success_symbol = "[>](green)"
error_symbol = "[x](red)"
vicmd_symbol = "[<](green)"

[git_branch]
symbol = ''
format = '\[[$symbol $branch]($style)\]'

[username]
style_user = "green bold"
style_root = "red bold"
format = "[$user]($style): "
show_always = true
